### ISSUE TITLE
Problems with diagnotics

### ISSUE THREAD

**Issue by ghx-0228** [bharatm11/Geomagic_Touch_ROS_Drivers#1]
I have set up the device connection successfully using LAN.
![image](https://user-images.githubusercontent.com/47413096/61436481-7c182f80-a96d-11e9-9e3e-4d377be592b1.png)
But there is still a problem when I diagnose the device.
![image](https://user-images.githubusercontent.com/47413096/61436661-dadda900-a96d-11e9-8958-7159d090774b.png)
Could you help me solve this?

**Comment by bharatm11** [comment]
Hi @ghx-0228,

This seems to be an issue with the Geomagic Driver and not the ROS driver. I am using a USB version and face this error when the appropriate permissions are not granted to the device. Do you want to check for firewalls?
@fsuarez6  do you have any ideas?

**Comment by fsuarez6** [comment]
No clue. I haven't even seem the new models. I worked with the FireWire version :D
Did you try the driver? The diagnostics tools tend to be picky.

**Comment by bharatm11** [comment]
@ghx-0228 were you able to fix it?

**Comment by ghx-0228** [comment]
Sorry, I have no idea. Now the official drivers are based on Ubuntu 14.04
and 18.04.  So I think maybe because of the incompatible versions between
Geomagic_Touch  driver and ROS(16.04).

**Comment by bharatm11** [comment]
@ghx-0228 it seems to be an unrelated issue. Both mine and the drivers by fsuarez6 are for the  USB and firewire models respectively. It seems like the Geomagic_Touch driver is unable to find the LAN device in your case

**Comment by ghx-0228** [comment]
A long time later I tried it again on my laptop. It works. I guess the Communication Error is related to the firewire.

**Comment by bharatm11** [comment]
Great! Thanks for letting me know, @ghx-0228 :)

**Comment by ghx-0228** [comment]
Dear Bharat

Recently, I wanna connect two haptic devices. But maybe the launch file
"omni_state.launch" seems to only support single device. Could you give any
suggestions to handle this issue?

Best Regards
Gao Huxin

**Comment by bharatm11** [comment]
Hi Gao,

I have never tried doing this before. Perhaps, changing the default com port and device name might let you connect the 2 devices. Keep me posted!

Best,
Bharat Mathur
