### ISSUE TITLE
error:Failed to initialize haptic device

### ISSUE THREAD

**Issue by qwewr** [bharatm11/Geomagic_Touch_ROS_Drivers#3]
hello
when I try to run roslaunch omni_common omni.launch, but I get this error:
![图片](https://user-images.githubusercontent.com/46448484/88290927-100f9a80-cd2a-11ea-89e4-e4910818b69c.png)
tank you for your help.

**Comment by QRayMoor** [comment]
Hi, there. I found this link is failed when I tried to install **Geomagic_Touch_ROS_Drivers** , do you know how to fix it?

> Download and Extract OpenHaptics and Haptic Device drivers

> Download drivers using instructions at: https://3dsystems.teamplatform.com/pages/102863?t=fptvcy2zbkcc

**Comment by bharatm11** [comment]
@QRayMoor The link seems to work fine for me. I have a link to a google drive with the drivers at the bottom of the readme.

**Comment by bharatm11** [comment]
@qwewr seems like you have a license issue. Are you sure that you are using the correct drivers?

**Comment by bsunal** [comment]
@QRayMoor Try this link. However, it does not work on Ubuntu 16.04. You may need to upgrade your system to 18.04.
https://support.3dsystems.com/s/article/OpenHaptics-for-Linux-Developer-Edition-v34?language=en_US

**Comment by 159chenJie159** [comment]
Hi,

I am having the same issue. Have you found a solution?

Thank you
