### ISSUE TITLE
Broken link of device driver

### ISSUE THREAD

**Issue by poyotamu000** [bharatm11/Geomagic_Touch_ROS_Drivers#6]
In Installation of README.md, there is a device drivers download link link below.

> 2. Download and Extract OpenHaptics and Haptic Device drivers
> Download drivers using instructions at: https://3dsystems.teamplatform.com/pages/102863?t=fptvcy2zbkcc

However, this download link is broken. 
Should I use an old device driver?
Please fix.

**Comment by bharatm11** [comment]
Fixed in pull request #9 . Thank you @poyotamu000 @pazeshun
